import fs from "node:fs";
import path from "node:path";

// TODO: accept an input instead.
const monorepoRoot = path.resolve(import.meta.dirname, "../..");

const flattened = flattenAllGitignores();
fs.writeFileSync(
  path.resolve(monorepoRoot, ".prettierignore"),
  flattened,
  "utf-8"
);

/**
 * Flatten all gitignores into a single one.
 *
 * @returns {string}
 */
function flattenAllGitignores() {
  const entries = fs.globSync(
    [".prettierignore-additions", ".gitignore", "**/*/.gitignore"],
    {
      cwd: monorepoRoot,
      exclude: ["**/node_modules/**"],
      withFileTypes: true,
    }
  );

  let prettierIgnore = [
    "################################################################################",
    "### This is a flattened ignore pattern list generated by flatten-gitignores. ###",
    "### See https://shirakaba/flatten-gitignores for documentation.              ###",
    "################################################################################",
    "",
    "",
  ].join("\n");

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }

    const contents = fs.readFileSync(
      path.resolve(entry.parentPath, entry.name),
      "utf-8"
    );

    // Create a relative path with a leading and trailing slash.
    const relativePath = path
      .relative(monorepoRoot, entry.parentPath)
      .replace(/^\/*/, "/")
      .replace(/\/*$/, "/");

    prettierIgnore += `### START ${relativePath}.gitignore ###\n`;

    const flattened = flattenGitignore({ contents, relativePath });

    prettierIgnore += `${flattened ?? "# (empty)"}\n`;

    prettierIgnore += `### END ${relativePath}.gitignore ###\n\n\n`;
  }

  return `${prettierIgnore.trim()}\n`;
}

/**
 * A best-effort function to rewrite all gitignore rules to be relative to a
 * given path.
 *
 * @param {object} args
 * @param {string} args.contents
 * @param {string} args.relativePath A relative path, with both a leading and
 * trailing slash.
 *
 * @see https://git-scm.com/docs/gitignore#_pattern_format
 */
function flattenGitignore({ contents, relativePath }) {
  let flattened = "";

  for (const line of contents.split("\n")) {
    if (!line || line.startsWith("#")) {
      flattened += `${line}\n`;
      continue;
    }

    if (line.startsWith("/")) {
      // String-replace to avoid writing // redundantly.
      flattened += `${relativePath}${line.replace(/^\/+/, "")}\n`;
    } else {
      // String-replace to avoid writing /**/**/ redundantly.
      flattened += `${relativePath}**/${line.replace(/^\*\*\/*/, "")}\n`;
    }
  }

  return flattened.trim();
}
